{% set name = "azure-batch" %}
{% set version = "13.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-batch-{{ version }}.zip
  sha256: e9295de70404d276eda0dd2253d76397439abe5d8f18c1fca199c49b8d6ae30a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - azure-common >=1.1,<2.0
    - msrest >=0.6.21
    - msrestazure >=0.4.32,<2.0.0

test:
  imports:
    - azure.batch
    - azure.batch.custom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Batch Client Library for Python
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://docs.microsoft.com/en-us/azure/developer/python/
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - xylar
